fixtures:
  - id: par_left
    type: par100
    address: 1
    mode: 7

  - id: par_right
    type: par100
    address: 17
    mode: 7

  - id: moving_head
    type: tmh13
    address: 33
    mode: 11

  - id: tetra
    type: tetra
    address: 49
    mode: 11

groups:
  pars:
    - par_left
    - par_right
  all:
    - par_left
    - par_right
    - moving_head
    - tetra
